// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmcPlDN5UG7Xre8dog1XKGwLSrjNpn-pI',
    appId: '1:1080194111365:web:4df23a82bda993ad1b96ec',
    messagingSenderId: '1080194111365',
    projectId: 'fir-login-demo-8a89a',
    authDomain: 'fir-login-demo-8a89a.firebaseapp.com',
    storageBucket: 'fir-login-demo-8a89a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2-pgJ3KXC0D4l-xqtDL5AdIWl_3MDCrk',
    appId: '1:1080194111365:android:7b839883958ed49d1b96ec',
    messagingSenderId: '1080194111365',
    projectId: 'fir-login-demo-8a89a',
    storageBucket: 'fir-login-demo-8a89a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8srhC49DnLjXsXWyNdtGBFQsbv5Eq-SY',
    appId: '1:1080194111365:ios:0ffd497b626095001b96ec',
    messagingSenderId: '1080194111365',
    projectId: 'fir-login-demo-8a89a',
    storageBucket: 'fir-login-demo-8a89a.appspot.com',
    iosBundleId: 'com.example.firebaseLoginDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8srhC49DnLjXsXWyNdtGBFQsbv5Eq-SY',
    appId: '1:1080194111365:ios:43e71dada270332b1b96ec',
    messagingSenderId: '1080194111365',
    projectId: 'fir-login-demo-8a89a',
    storageBucket: 'fir-login-demo-8a89a.appspot.com',
    iosBundleId: 'com.example.firebaseLoginDemo.RunnerTests',
  );
}
